In [19]:
from google.colab import drive

# This will prompt for authorization.
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import pandas as pd
import numpy as np
import itertools

In [0]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer
num_periods_output=12
num_periods_input=24

def preprocessing(df,num_features):
    
    Number_Of_Features=num_features
    

    '''df=df.drop(['LastUpdate'],axis=1)
    #print(df.iloc[:,5])
    ################################################encoding####################
    df['Occupancy'] = pd.to_numeric(df['Occupancy'],errors='coerce')
    df['Occupancy'] = df['Occupancy'].abs()
    
    Status=df.pop('Status')
    df.loc[:,'Status_filling']=(Status=='Filling')*1.0
    df.loc[:,'Status_static']=(Status=='Static')*1.0
    df.loc[:,'Status_emptying']=(Status=='Emptying')*1.0
    DayOfWeek=df.pop('DayOfWeek')
    df.loc[:,'DayOfWeek_0']=(DayOfWeek==0)*1.0
    df.loc[:,'DayOfWeek_1']=(DayOfWeek==1)*1.0
    df.loc[:,'DayOfWeek_2']=(DayOfWeek==2)*1.0
    df.loc[:,'DayOfWeek_3']=(DayOfWeek==3)*1.0
    df.loc[:,'DayOfWeek_4']=(DayOfWeek==4)*1.0
    df.loc[:,'DayOfWeek_5']=(DayOfWeek==5)*1.0
    df.loc[:,'DayOfWeek_6']=(DayOfWeek==6)*1.0
    
    
    df=df.values
    df = df.astype('float32')
    split=num_periods_output+num_periods_input
    '''
    ##################################SPLIT##############################################
    
    ########################### SPLITTING FOR TRAIN ###########################
    train_len=np.floor(len(df)*0.8)
    mod=train_len%(num_periods_input+num_periods_output)
    #let thelength be divisable by 12
    train_len=int(train_len-mod)
    Train=df[0:train_len]
    ######################### SPLITTING FOR VALIDATION ########################
    #valid_len=np.floor(len(df)*0.1)
    #mod=valid_len%(num_periods_input+num_periods_output)
    #let thelength be divisable by 12
    #valid_len=int(valid_len-mod)
    #Valid=df[train_len:(train_len+valid_len),:]
    ########################## SPLITTING FOR TESTING ##########################
    test_len=np.floor(len(df)*0.2)
    #test_len=np.floor(len(df)*0.01)
    mod=test_len%(num_periods_input+num_periods_output)
    #let thelength be divisable by 12
    test_len=int(test_len-mod)
    Test=df[len(df)-test_len:len(df)]
    #Test=df[len(df)-test_len:len(df),:]
    #############################  Normalization on train and validation separatly  #############
    '''
    ID_Train=Train[:,6]
    Train=np.delete(Train,[6],1)
    #x_batches=x_batches.drop(columns=['ID'], axis=1)
    occ_Train=Train[:,5]
    Train=np.delete(Train,[5],1)
    #x_batches=x_batches.drop(columns=['Occupancy'], axis=1)
    #normalizing data
    Train = Train.astype('float32')
    normalizer = Normalizer().fit(Train)
    Train=normalizer.transform(Train)
    
    ID_Valid=Valid[:,0]
    Valid=np.delete(Valid,[0],1)
    #X_test=X_test.drop(columns=['ID'], axis=1)
    occ_Valid=Valid[:,0]
    Valid=np.delete(Valid,[0],1)
    #X_test=X_test.drop(columns=['Occupancy'], axis=1)
    Valid = Valid.astype('float32')
    Valid=normalizer.transform(Valid)
    #------------------
    ID_Train=np.reshape(ID_Train,(len(ID_Train),1))
    occ_Train=np.reshape(occ_Train,(len(occ_Train),1))
    
    Train=np.append(occ_Train, Train, axis=1)
    Train=np.append(ID_Train, Train, axis=1)
    #------------------
    ID_Valid=np.reshape(ID_Valid,(len(ID_Valid),1))
    occ_Valid=np.reshape(occ_Valid,(len(occ_Valid),1))
    
    Valid=np.append(occ_Valid,Valid, axis=1)
    Valid=np.append(ID_Valid, Valid, axis=1)'''
    
    ############################################ TRAIN minibatches ##################################
    
    end=len(Train)
    start=0
    next=0
    x_batches=[]
    y_batches=[]
    
    #print('lennnn',len(Train))
    while next+num_periods_input<end:
        next=start+num_periods_input
        x_batches.append(Train[start:next])
        y_batches.append(Train[next:next+num_periods_output])
        start=start+1
    y_batches=np.asarray(y_batches)
    y_batches = y_batches.reshape(-1, num_periods_output, 1)   
    x_batches=np.asarray(x_batches)
    x_batches = x_batches.reshape(-1, num_periods_input, Number_Of_Features)   
    
    ############################################ VALID minibatches ##################################
    '''
    end_val=len(Valid)
    start_val=0
    next_val=0
    x_validbatches=[]
    y_validbatches=[]
    
    #print('lennnn',len(Train))
    while next_val+num_periods_input<end_val:
        next_val=start_val+num_periods_input
        x_validbatches.append(Valid[start_val:next_val,:])
        #print('input for X:  ',Valid[start_val:next_val,:])
        y_validbatches.append(Valid[next_val:next_val+num_periods_output,1])
        #print('input for Y:  ',Valid[next_val:next_val+num_periods_output,1])
        start_val=start_val+1
    y_validbatches=np.asarray(y_validbatches)
    y_validbatches = y_validbatches.reshape(-1, num_periods_output, 1)   
    x_validbatches=np.asarray(x_validbatches)
    x_validbatches = x_validbatches.reshape(-1, num_periods_input, Number_Of_Features)  ''' 
    
    ###########################################TEST#####################################
    '''
    ID_Test=Test[:,6]
    #print(ID_Test)
    Test=np.delete(Test,[6],1)
    #X_test=X_test.drop(columns=['ID'], axis=1)
    occ_Test=Test[:,5]
    #print(occ_Test)
    Test=np.delete(Test,[5],1)
    #X_test=X_test.drop(columns=['Occupancy'], axis=1)
    Test = Test.astype('float32')
    Test=normalizer.transform(Test)
    
    #------------------
    ID_Test=np.reshape(ID_Test,(len(ID_Test),1))
    occ_Test=np.reshape(occ_Test,(len(occ_Test),1))
    
    Test=np.append(occ_Test,Test, axis=1)
    #print(Test)
    Test=np.append(ID_Test, Test, axis=1)
    #print(Test)'''
    ############################################ TEST minibatches ##################################
    end_test=len(Test)
    start_test=0
    next_test=0
    x_testbatches=[]
    y_testbatches=[]
    
    
    #print('lennnn',len(Train))
    while next_test+num_periods_input<end_test:
        next_test=start_test+num_periods_input
        x_testbatches.append(Test[start_test:next_test])
        y_testbatches.append(Test[next_test:next_test+num_periods_output])
        start_test=start_test+1
    y_testbatches=np.asarray(y_testbatches)
    y_testbatches = y_testbatches.reshape(-1, num_periods_output, 1)   
    x_testbatches=np.asarray(x_testbatches)
    x_testbatches = x_testbatches.reshape(-1, num_periods_input, Number_Of_Features)  
    
    return x_batches, y_batches, x_testbatches, y_testbatches

In [0]:
#filepath = 'C:/Users/chamu/Documents/Python Scripts/Parking Project/Naive Forecast/half_data_15/BN00'
filepath = '/content/drive/My Drive/FINAL_DATA_EVENTS/BN00'


In [0]:
def compute_se(prediction,actual):
    
    return (prediction-actual)**2

In [0]:
def compute_rmse(se_list):
    se = 0
    
    for i in range(0,len(se_list)):
        se = se + se_list[i]
        #print(se)
        
    rmse = np.sqrt(se/len(se_list))
    
    return rmse

In [25]:
se_list = []
for file in range(1,9):
    path = filepath + str(file) + '.csv'
    BN = pd.read_csv(path, sep=',', index_col = None)
    if BN.ID[0]!=7 and BN.ID[0]!=8:
        print(BN.Year.unique())
        BN=BN[(BN.Year==2017) | (BN.Year==2018)]
        #.isin(years)
        #print(df.loc[df['Year'].isin([2017,2018])])
        print(BN.Year.unique())
        #print(df.Capacity.unique())
    else:
        BN=BN[(BN.Year==2015) | (BN.Year==2016)]
        print(BN.Year.unique())
        #print(df.Capacity.unique())
    BN = BN[ 'Occupancy'].values
    #print(BN)
    #BN = BN.sort_values(by=['LastUpdate'])
    window_size=24
    x_batches_Full=[]
    y_batches_Full=[]
    X_Test_Full=[]
    Y_Test_Full=[]
    x_batches, y_batches,X_Test,Y_Test=preprocessing(BN,1)
    #===============================
    for element1 in (x_batches):
        x_batches_Full.append(element1)
            
    for element2 in (y_batches):
        y_batches_Full.append(element2)
                        
    for element5 in (X_Test):
        X_Test_Full.append(element5)
            
    for element6 in (Y_Test):
        Y_Test_Full.append(element6)
    
    #ground_truth = BN['Occupancy'].tolist() 
     
    
    #prediction = ground_truth[0]  #predicts the last_value seen 
    
    for i in range(0,len(X_Test_Full)):
      for j in range(0,num_periods_output):
        
        actual_value = Y_Test_Full[i][j]
        
        prediction = X_Test_Full[i][j+12]  #predicts the last_value        
        #print(actual_value,'  prediction ',prediction)
        se_list.append(compute_se(prediction,actual_value))

[2014 2015 2016 2017 2018 2019]
[2017 2018]
[2014 2015 2016 2017 2018 2019]
[2017 2018]
[2014 2015 2016 2017 2018 2019]
[2017 2018]
[2015 2016 2017 2018 2019]
[2017 2018]
[2014 2015 2016 2017 2018 2019]
[2017 2018]
[2014 2015 2016 2017 2018 2019]
[2017 2018]
[2015 2016]
[2015 2016]


In [0]:
RMSE = compute_rmse(se_list)

In [27]:
print('RMSE: {}'.format(RMSE))

RMSE: [13.96773168]
